---
- name: Install required packages
  apt:
    name: "{{ item }}"
  with_items:
    - curl
    - tar
    - bzip2
    - ca-certificates
    - ssl-cert

- name: Add grafana sources.list
  notify: update apt
  copy:
    dest: /etc/apt/sources.list.d/grafana.list
    content: |
      deb https://packages.grafana.com/oss/deb stable main
- name: Add grafana apt key
  notify: update apt
  apt_key: url=https://packagecloud.io/gpg.key

- name: Disable password ssh logins
  notify: restart sshd
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication .*" line="PasswordAuthentication no"
